name: SpawnerPickaxe
version: 3.0.4
main : fr.hegsis.spawnerpickaxe.Main
description: A usefull way to play with a spawner
author: HegSiS
api-version: 1.13
depend:
  - Vault
commands:
  superspawnerpickaxe:
    aliases: [ssp, sspickaxe, supersp]
    description: All commands concerned with super spawner pickaxe
  spawnerpickaxe:
    aliases: [ps, spickaxe, spawnerp]
    description: All commands concerned with spawner pickaxe
  spawner:
    description: Show / Summon spawners
  entity:
    description: Manage entity
    aliases: ent