package fr.hegsis.spawnerpickaxe.manager;

public enum Option {
    FACTION,
    TNT_BREAK_SPAWNER,
    SUPERSPAWNERPICKAXE,
    PLAYER_HEAD_IN_MENU,
    RIGHT_CLICK_SPAWNER_MENU,
    SPAWNERPICKAXE_SHOP,
    SPAWNERPICKAXE_SIGN,
    SPAWNERLIST_MENU
}
